x-maven-openjdk-volumes: &maven-openjdk-volumes
  - ./.m2:/root/.m2
  - ./:/tmp

x-jre-volumes: &jre-volumes
  - ./target:/tmp

secrets:
  postgres-password:
    file: ./secrets/postgres_password.txt

x-db-volumes: &db-volumes
#  - ./postgres_data:/var/lib/postgresql/data:rw,z,U
#  - postgres-vol:/var/lib/postgresql/data:rw,z,U
  - postgres_vol:/var/lib/postgresql/data
  - ./init.sql:/docker-entrypoint-initdb.d/init.sql

version: '3.7'

services:
  build:
    container_name: maven-3-8-4-openjdk-17
    image: docker.io/maven:3.8.4-openjdk-17
    #    image: harbor.cluster.pve.perso.relativite.ovh/store/maven:3.8.4-openjdk-11
    #    image: cache-ili.univ-artois.fr/proxy_cache/library/maven:3.8.4-openjdk-11
    volumes: *maven-openjdk-volumes
    tty: true
    command: "/bin/bash"
    working_dir: /tmp

  run:
    container_name: eclipse-temurin-17-jre-focal
    image: docker.io/eclipse-temurin:17-jre-focal
    ports:
      - 8080:8080
    expose:
      - "8080"
    #    network_mode: host
    volumes: *jre-volumes
    tty: true
    command: "/bin/bash"
    working_dir: /tmp
    depends_on:
      db:
        condition: service_healthy
#    entrypoint: java -Dspring.profiles.active=development ${JAVA_OPTS} -Xmx${javaMemoryLimit} -jar /app.jar
    entrypoint: java -Dspring.profiles.active=development -jar pogues-bo.jar

  db:
    image: postgres:16.1
    container_name: postgres-dev-with-volumes
    hostname: postgres-dev
    privileged: true
    environment:
      - POSTGRES_USER=pogues
      - POSTGRES_DB=pogues
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    secrets:
      - postgres-password
    volumes: *db-volumes
#    volumes:
#      - postgres_vol:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
    - "5432"
    ports:
      - 5432:5432
#    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 30s
      retries: 3

volumes:
  postgres_vol:
#  test_vol:
